image: ruby:2.7

variables:
  PAGES_REPO_NWO: DevoInc/devoinc.github.io.git

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

cache:
  paths:
    - vendor/

before_script:
  - gem install bundler
  - bundle install --path vendor

pages:
  stage: deploy
  script:
    #- bundle exec jekyll build --config _config.yml,config_test.yml -d public
    - bundle exec jekyll build --baseurl=https://rad.pages.devotools.com/talks-and-blog/blog/ -d public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

test:
  stage: test
  script:
    - bundle exec jekyll build --config _config.yml,config_test.yml -d test
  artifacts:
    paths:
      - test
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
